### ISSUE TITLE
marginal low-priority notation question

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#10]
On 3x3x3,  when a parameter movetext is set to 1, d move (i.e. D E moves) is shown as Dt, even though in the source code is written "d". Similarly for other moves which turn inner and outer layer simultaneously. 

Would it be possible to express one move by one letter (e.g. d by d instead of Dt) in movetext=1 option?

**Comment by mfeather1** [comment]
Try movetext=2

**Comment by bcube2** [comment]
Your advice fixed my problem/question. Thank you. This issue can be closed now.

**Comment by bcube2** [comment]
I don't want to make another issue, so I will just use this one before getting closed...

Michael, on your http://irbsystems.com/test2/rc/AnimCube4/test.html there is a broken link about supercube documentation (you have one more rc/ inside the link). It was working before so you must have been editing it somehow...

And I noticed JS files on this github were updated. Any announcement you would like to share or was it only some minor change which doesn't influence its appearance/behaviour?

**Comment by mfeather1** [comment]
The original link I gave to that page was:
http://irbsystems.com/test2/animcube4/test.html
That directory is a symbolic link from rc/AnimCube4, I put the full path in so it works either way now.
The last update was for Supercube for 3x3.  I didn't put 4x4 in there, as you know it's a different set of JS files so I was wondering what is the best way to put them in Github so they are separate (3x3 vs 4x4) but still both contained in one download, either that or just leave the 4x4 on my web-site.
