### ISSUE TITLE
Request for permission: Integration in my plugin

### ISSUE THREAD

**Issue by blonkm** [cubing/AnimCubeJS#12]
I have developed a WordPress plugin for easy integration of Rubik's cubes on websites, for people who don't know HTML or programming. It was based on Java cubes, but I recently updated it to work with my WebGL cube. I would like to integrate AnimCubeJS into my plugin and request permission to do so, leaving all copyright notices and a link to the demo site of course. You can download it on [my plugin page](http://www.vanderblonk.com/tools/wordpress-rubik-plugin/) (not guaranteed to work, still in alpha).

**Comment by mfeather1** [comment]
You can use AnimCubeJS however you like.  I didn't think there was any copyright notices in AnimCubeJS.  There's one in the html file that calls AnimCube on my web-site but that's just standard boilerplate that comes from the Ant build that I never bothered to do anything with (I guess I'll have to read it...).  In my html I have  "Unique Cube Solving Method Copyright 1980 By Michael Feather" which I put there largely to make a point that I came up with it when the cube first came out (completely independently) and also in case someone else makes a $billion selling 3-color and Starter Cubes so they wouldn't completely cut me out of the picture (at least leave my name in the footnotes somewhere as having contributed).  :)

**Comment by blonkm** [comment]
OK, Michael, thanks a bunch. Closing.
