### ISSUE TITLE
broken link in readme.md

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#13]
Hi,

there is a broken link (see "unminified code") in readme.md. Nothing important, as it is irrelevant to the simulator itself.

Edit: working now, trying to close this issue. Seems like I succeeded :-)

P.S. I noticed that on both http://irbsystems.com/test2/rc/AnimCube/ and this github there are the same .cache.js files, whereas on http://irbsystems.com/test2/rc/AnimCube/unminified/NOTE there are different minified files (at least different names of minified files), so I assume those unminified files are a little bit outdated.

**Comment by mfeather1** [comment]
Yes, unminified is old version.  The source code used for development is the .java file and the unminified files are what gets generated from the GWT build. Unless the unminified files are of use to anyone (and I don't know why they would be) then I probably won't be updating them any time soon.  They are there to show what the generated JS code looks like but of little use for development (unless, I suppose, one were to try to convert them into something more developer friendly, but considering there are five versions for the different browser engines and they are 6000 lines each I don't see that happening).  However, they can be provided upon request, I will probably update them after I get to the point where I'm no longer updating the java code.
