### ISSUE TITLE
AnimCube 2x2 html file

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#14]
I didn´t manage to run big 2x2x2 cube in a .html file on localhost. I can see it on http://www.irbsystems.com/test2/rc/AnimCube2.html, I don´t see .html file on http://www.irbsystems.com/test2/rc/AnimCube2/ (in test.html the 2x2x2 cubes can not be seen).

In previous versions the .html file was always called cube, so I tried that - still not working. I tried to rename it to AnimCube2.html (as on Michael´s site) - not working. On github, there is cube2.html - not working.

Please help.

At the moment I just copied cube.html from working 5x5x5 folder on my localhost, changed src (instead of animcube5.nocache.js I named it animcube2.nocache.js), so it looks like this (currently it is named cube.html (because tis name works for both 3x3x3, 4x4x4 and 5x5x5 on localhost)):

<!DOCTYPE html>
<html>
  <head>
    <meta name="robots" content="noindex,nofollow">
    <script src="animcube2.nocache.js"></script>
    <title>AnimCube</title>
  </head>
  <body style="padding:0;margin:0;overflow:hidden">
    <noscript>Povolte si javascript v prohlížeči a uvidíte kostku na tomto místě.</noscript>
  </body>
  <div style="display:none"><endora></div>
</html>

cube.html is in the same folder as animcube2.nocache.js (as well as other 5 .js files), the structure is the same as for working 3x3x3, 4x4x4 and 5x5x5 cubes.

**Comment by bcube2** [comment]
Edit: I removed brackets in tags from the source code so that it could be seen on github. Here it is (don´t mind endora tag):

!DOCTYPE html
html
  head
    meta name="robots" content="noindex,nofollow"
    script src="animcube2.nocache.js"/script
    titleAnimCube/title
  /head
  body style="padding:0;margin:0;overflow:hidden"
    noscriptPovolte si javascript v prohlížeči a uvidíte kostku na tomto místě./noscript
  /body
  div style="display:none"endora>/div
/html

**Comment by bcube2** [comment]
Found and solved the issue. For some reason I thought github is user-friendly (it turned out to be a fatal mistake for me as a computer greenhorn). 

Initially I downloaded .js files from https://github.com/cubing/AnimCubeJS/tree/gh-pages/animcube/2x2. When I opened them, I figured out all of them are just html files. After downloading 6 .js files from Michael´s site (see post no. 1 in this thread), big cube showed up immediately :-)

Closing.

**Comment by bcube2** [comment]
Found and solved the issue. For some reason I thought github is user-friendly (it turned out to be a fatal mistake for me as a computer greenhorn). 

Initially I downloaded .js files from https://github.com/cubing/AnimCubeJS/tree/gh-pages/animcube/2x2. When I opened them, I figured out all of them are just html files. After downloading 6 .js files from Michael´s site (see post no. 1 in this thread), big cube showed up immediately :-)

Closing.

**Comment by mfeather1** [comment]
If the complete zip file is downloaded from GitHub it should work without having to mess with anything.  If that is not the case for you then let me know and I'll look into it some more but it works for me so I don't see an issue.  The file cube_sizes.html has all the cubes sizes and is linked to the main page (both at github and locally (when downloaded file is unzipped)).
