### ISSUE TITLE
the direction of the arrow changes.

### ISSUE THREAD

**Issue by ynssn** [cubing/AnimCubeJS#17]
Hello

I am not good at English, so I post the translated sentences.
I am sorry if it is difficult to understand.

When "Bm" is given to 3x3 super cube, the direction of the arrow changes.
This problem does not occur with "Fm '" which has the same behavior.

![cube](https://user-images.githubusercontent.com/50923397/58194277-10646e00-7d00-11e9-84a4-2580d3b6e5d4.gif)

**Comment by mfeather1** [comment]
Hi, thanks for your feedback on AnimCubeJS, try the cube at the following link:
https://mfeather1.github.io/test/test8/3x3/scbm.html

**Comment by ynssn** [comment]
The problem is solved.
Thank you for your prompt response.
