### ISSUE TITLE
[Feature Request] Support programatic control of the cube.

### ISSUE THREAD

**Issue by 7ombie** [cubing/AnimCubeJS#18]
While AnimCubeJS is great for animating hardcoded stuff, the mouse-based controls are too awkward and unpredictable to use the cube as a virtual Rubik's Cube. The controls are also broken (the wrong layer is often selected), and they provide no way to move two layers at the same time or reset the view of the cube etc.

An API for manipulating the cube (really the camera) and its layers would allow users to integrate AnimCubeJS into their own applications.

I'd personally like to bind a gamepad, but it would be just as simple to bind a keyboard or MIDI controller, if there was an API for that. Thanks for considering this.

**Comment by 7ombie** [comment]
P.S. If an API was added, the configuration (file) should permit disabling the mouse-based controls.

**Comment by lgarron** [comment]
Depending on exactly what you're trying to do, `cubing.js` might already have everything you need:

https://codepen.io/lgarron/pen/BaZerqe?editors=1010
https://twizzle.net/stream/ might be more convenient to use directly as well.

Let me know if you'd like any help trying those out.

**Comment by 7ombie** [comment]
Thanks, @lgarron. I'll look at those links. Much appreciated.
