### ISSUE TITLE
Request function:  facelet editor that would output a facelet string.

### ISSUE THREAD

**Issue by wu18** [cubing/AnimCubeJS#21]
I am currently trying to use AnimCubeJS to write a Cube solving tutorial.

I want to show all intermediate steps.
As such, I want to use the facelets parameter to show the cube in various states and a lot of the times I want to mark many of the face pieces to be black or gray.

The facelets parm is nice.  I find it very difficult to look at that table and the numbering to come up with a proper facelet string.
It would be nice if there is a facelet editor that would allow us to just edit the cube and then output the facelet string.

I wish the string itself can allow empty space so that we can separate the six 9 digit groups for each face, currently it doesn't allow blank in the string.

**Comment by bcube2** [comment]
I can not solve your problem, however:

- a facelet editor allowing us to edit the cube can be created, see https://mfeather1.github.io/3ColorCube/solver/solve.html?stl=5s&snc=1&use_p2seq=1 and https://mfeather1.github.io/3ColorCube/text_input_cube.html

- a facelet string output can be created, see https://cubing.github.io/AnimCubeJS/sources/codes/enhancement/cube_var.html

**Comment by wu18** [comment]
> Collaborator

Thank you very much for the info!

The  facelet string output is useful by using our own cube variable.
The text_input_cube.html example is nice.  I think I can use it as my facelet editor to get the string I want.  

I have two comments for the text_input_cube.html:
(1) the apply moves doesn't seem to work, it only works if the move is one character  (say: R.  if I put RFD, it would not apply the moves)
(2)  if I modify the face color and then click on "show", it works -- it updates the color on the cube.
However, if I check the "AnimCube Format" checkbox first, and then click on the "show" button, then it doesn't work.

I think we should have this "text_input_cube.html" file as of the AnimCubeJS source for codes enhancement.
It makes it easy to get the proper facelet string.

**Comment by bcube2** [comment]
I am glad I could help.

> I have two comments for the text_input_cube.html

If you click on the Help button, you will be linked here: https://mfeather1.github.io/3ColorCube/text_input_help.html. Please read that page as I believe both your comments are covered there.

> I think we should have this "text_input_cube.html" file as of the AnimCubeJS source for codes enhancement.
It makes it easy to get the proper facelet string.

I think most users won´t have troubles with the facelets string whatsoever. However, I will be thinking about it, thank you for your suggestion.

If you want to see some other examples of AnimCubeJS functionality, check out the Solving Demos and Interactive sections at https://mfeather1.github.io/3ColorCube/idx.html by Michael Feather.

**Comment by wu18** [comment]
Thank you!
