### ISSUE TITLE
Moving domains

### ISSUE THREAD

**Issue by lgarron** [cubing/AnimCubeJS#22]
Ahoy!

I'm trying to remove our dependence on `cubing.github.io`: https://github.com/cubing/infra/issues/3

Could I ask to move this project to a `cubing.net` subdomain, such as `animcube-js.cubing.net`?
(The hosting would work exactly the same using GitHub Pages and old URLs would redirect.)

**Comment by bcube2** [comment]
Hi lgarron,

thank you for your proposal, we are fine with it. As a subdomain, please use `animcubejs.cubing.net`. Thank you.

**Comment by lgarron** [comment]
Now serving: https://animcubejs.cubing.net/animcubejs.html
(Also feel free to add a root `index.html` as you see fit.)

And the redirect is in place: https://cubing.github.io/AnimCubeJS/animcubejs.html

Thanks!

**Comment by lgarron** [comment]
I'd also like to add `animcubejs.cubing.net` to the index at https://cubing.net/ — if you're alright with that, is there any particular way you'd like to be credited, @bcube2 and @mfeather1?

**Comment by bcube2** [comment]
> I'd also like to add animcubejs.cubing.net to the index at https://cubing.net/ — if you're alright with that

Thank you, I am alright with that :-)

> is there any particular way you'd like to be credited?

I haven´t really been programming anything in this project, so I don´t need to be credited. I would prefer to credit the following guys, in that order: Michael Feather, Josef Jelinek

**Comment by mfeather1** [comment]
I would suggest this order: Josef Jelínek, Tadeáš Miler, Michael Feather.

**Comment by lgarron** [comment]
> I would suggest this order: Josef Jelínek, Tadeáš Miler, Michael Feather.

Added at https://www.cubing.net/ !
