### ISSUE TITLE
Customizing Corner Roundness

### ISSUE THREAD

**Issue by Technet8394** [cubing/AnimCubeJS#23]
For context, I code mainly in PowerShell.

I am making a graphic design project that needs a cube animation and I know enough Javascript/HTML to be comfortable using this. I would like to change the corners to be a bit rounder to fit in with the theme of the project. Is there an easy way to do this or is javascript limited to perfect cubes?

Thanks in advance! Zane

**Comment by raquelhortab** [comment]
hi! @Technet8394  did you  finally achieve this?

**Comment by Technet8394** [comment]
I ended up making it in After Effects, i did not get it to work. Sorry for responding late, was in Canada and had no access to the internet.

**Comment by bcube2** [comment]
[Florian mod](https://animcubejs.cubing.net/sources/codes/enhancement/florian.html) has been added to the [Enhancement](https://animcubejs.cubing.net/animcubejs.html#enhancement) section, see if you like it better.
