### ISSUE TITLE
AnimCube7

### ISSUE THREAD

**Issue by mfo13** [cubing/AnimCubeJS#24]
Dear developers, I love this code, lightweight and as far as I know it works in all platforms. I'm trying to extend your code for a 7x7x7 cube. After a bunch of time I could realize how the main code and functions, specially matrices and stuff, work and was able to extend the script; however I still need to fix the superlayer twists as well as the notation. If you could explain the logic behind superTwistArr array and twistSuperLayer function it would save a lot of time. I'll try figure out how the notation works later on. Thank you.

**Comment by mfeather1** [comment]
See if this helps:
 https://drive.google.com/file/d/1rDlTtlAdRkvEj8TMZuk2Lk_2oSBqybet/view?usp=share_link

**Comment by mfo13** [comment]
Thank you, but I've already figured out...It is working. By the way this document is quite helpfull! I wish the rest of the script was so well documented. Anyway, now I'll move to notations, if you have any details regarding the logic behind, that would be great.

**Comment by mfeather1** [comment]
Assign a new letter for the second inner layer and add it to the convertNotation function:
function convertNotation7(s) {
  s = replaceMoves(s, 2, 'n');
  s = replaceMoves(s, 3, 'o');
  s = replaceMoves(s, 4, 'm');
  return s;
}
The second inner layer can then be turned with either "o" suffix or 3 prefix.

Also:

A new row needs added to each notation type in the turnSymbol array, and the modeChar, eyeOrder and blockMode arrays need updated.

Several lines need updated to account for the new "o" symbol, the 28 needs changed to 32 in the following lines and also "% 7" needs changed to "% 8":

            mv[length] = moveCodes[j] * 28;
    var s = turnSymbol[moveText - 1][Math.floor(move[pos] / 4) % 7][Math.floor(move[pos] / 28)];
    var mode = Math.floor(turn / 4) % 7;
        var mode = Math.floor(move[position] / 4) % 7;
        twistLayers(cube, Math.floor(move[position] / 28), modifier, mode);
          var mode = Math.floor(mv[movePos] / 4) % 7;
          var layer = Math.floor(mv[movePos] / 28);
            mode = Math.floor(mv[movePos] / 4) % 7;
            layer = Math.floor(mv[movePos] / 28);

The 7 can be changed to modeChar.length+1 and the 28 can be changed to (modeChar.length+1)*4 which would make it easier to add modeChars.

**Comment by mfo13** [comment]
OK! So it works, the movements are properly done! But the displayed text is a real mess :)
For example,
Given sequence: R  Rn Ro Rm Rt Ra Rs Rc  E   S  M 
Displayed text:    Ra Ro Rs Ra  R  Rc Rt Rn Dn Ft Ls (movetext=1)
Displayed text:    Ra 3R Rs Ra  R   x   r  2R 2D  f   Ls (sign=1)
The others movetext options display nothing.

There is clear wrong step size in some function related to text displaying... any hint?

**Comment by mfeather1** [comment]
I would need to see the code.

**Comment by mfo13** [comment]
Problem solved! I forgot a "+1" in turnSymbol...  ¯\_(ツ)_/¯
It is working! I just need to check all the functionalities and I think it is done!
After that I can send the code, so you guys could check, do a final polishing and perhaps you find useful to publish. However I don't know how to do that...

**Comment by mfo13** [comment]
Finished! All functionatilites are working properly, unless the following bellow: 
movetext = 2, 3 and 4; scw = 0, 1 and 2.
However such parameters don't work with AnimCubes 4, 5 and 6 either. So I think it is done. How can I send you the code?

**Comment by mfeather1** [comment]
You can send it to ymoua450@gmail.com.  If it is ok with you I will make it public (readonly) in my test repo for the purpose of testing.

You are correct, only movetext 1 & 5 are implemented for AnimCube4-6.

The scw parameter appears to be working at:
https://animcubejs.cubing.net/sources/codes/enhancement/parameters/create.html

Set to 6x6 and use the following with scw=0, 1 or 2:

scw=2&supercube=1&facelets=RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRROOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

**Comment by mfo13** [comment]
OK! scw works for 7x7x7 either! So the only remaining issue is that regarding movetext. I'll send you the code. Appart the modifications regarding the extention to 7x7x7x, please pay attention on comments at lines 1793, 1803, 2204 and 2251. I've made few modifications (not related to the 7x7x7) and perhaps you want to return them back to the original. 1793 and 1803 are related to a minor issue I've found in all cubes (I made a temporary amendment not really fixed it). 2204 and 2251 are just personal preferences :)

**Comment by mfeather1** [comment]
Awesome!  Thank you very much!  

I have it set up for testing here:
https://mfeather1.github.io/test/create.html
(select 7x7x7)

**Comment by mfo13** [comment]
It works! Thank you!

**Comment by bcube2** [comment]
Please ignore this post if:

a) it doesn´t belong to this issue (this issue is solved as I understand it)
b) the pictures below represent what mfo13 said [above](https://github.com/cubing/AnimCubeJS/issues/24#issuecomment-1480261627)

Regarding graphical appearance, I noticed these minor differences (excluding the size of the button symbols) between the inner face of a 7x7x7 cube and a 6x6x6 cube:

![a](https://user-images.githubusercontent.com/12406850/227210607-76ba8ba2-ef60-4a45-9714-0012b576590c.png)
![b](https://user-images.githubusercontent.com/12406850/227210615-617c33c0-8e9a-4906-87e1-95cc19bc7677.png)
![c](https://user-images.githubusercontent.com/12406850/227210618-620c5736-a8fa-4446-9a27-93062438b486.png)

**Comment by mfeather1** [comment]
I made a modified version at:
https://mfeather1.github.io/test/create.html
(these mods are not related to bcube's issue above)

There are 3 mods:

1. modified randcube function so it twists "o" layer and not "m" layer (we have chosen fixed-center model so middle layer is not twisted for 3x3, 5x5, 7x7).

2. modified supertwist code by putting all params in the array to make it more readable/understandable (hopefully) for larger cubes (the code that I evolved from 3x3 was in need of consolidation and now seems like a good time to do it).

3. added inner black faces for modes "t", "s","a" to function innerFacePosition (the inner black faces can be seen by commenting out the whole "else" section for the first if statement in the section where it says: "find and draw black inner faces").

**Comment by mfo13** [comment]
The issues that bcube2 mentioned above are remanescents of the amendment that I did trying to solve the issues that appear in all the cubes (see bellow), but because in 7x7x7 the layers are thinner such issues are more evident. The example bellow is from the 6x6x6.

![issue twist 1](https://user-images.githubusercontent.com/128325284/227349469-c4dc0201-586b-442d-bf92-86d82abec42c.png)
![issue twist 2](https://user-images.githubusercontent.com/128325284/227349663-87d830a9-db54-499b-8b39-b0a523ac555a.png)

**Comment by bcube2** [comment]
> The issues that bcube2 mentioned above are remanescents of the amendment that I did trying to solve the issues that appear in all the cubes (see bellow), but because in 7x7x7 the layers are thinner such issues are more evident.

I am sorry, I can´t reproduce the artifacts on my 3 pictures on any other cube than the 7x7x7.

I can reproduce the artifact on your second picture only when the borderwidth parameter is not set to the default value (i.e. I can reproduce it for both the gabbacolors=1 setting and the borderwidth=6 setting, but I can´t reproduce it for the borderwidth=10 setting).

**Comment by mfeather1** [comment]
The original 3x3 AnimCube.java program (by Josef) had neither the perspective correction nor the "if (call < N) ..." in the section "find and draw black inner faces", those are both workarounds that I used for the issues being discussed.  With these workarounds there does not appear to be a solution that solves all of these issues  (or if there is I'm not seeing it).

I added "6x6 modified" with the additional perspective correction to https://mfeather1.github.io/test/create.html where the issue similar to 7x7 can be seen (gray area inside rotated layer).  

Also added "7x7 modified 2" with the additional perspective correction removed where you can no longer see the gray inside the rotated layer but then it's got the other problem, the inner black face partially overlays the adjacent colored facelets.  These workarounds are trading off one set of issues for another.

**Comment by mfo13** [comment]
In (modified) I could reproduce the issue reported by bcube2 and in (modified 2) I could reproduce the issue already reported by me, see bellow. Both cases using the default configuration of the test page. They are mutualy exclusive. I think you need to choose one to keep...

![Screenshot_20230323_223313_Chrome](https://user-images.githubusercontent.com/128325284/227403760-214f41d2-c1fc-4586-838a-bf818fc51738.jpg)
![Screenshot_20230323_223338_Chrome](https://user-images.githubusercontent.com/128325284/227403763-4c711c95-056e-4c41-8eef-497f07da9b89.jpg)
![Screenshot_20230323_223510_Chrome](https://user-images.githubusercontent.com/128325284/227403765-336f4cfc-e1b2-4d0f-82f5-cde401beefc3.jpg)
![Screenshot_20230323_223541_Chrome](https://user-images.githubusercontent.com/128325284/227403767-b2a0d2f7-d58e-4d0c-b720-ed28e831381a.jpg)

**Comment by mfeather1** [comment]
Agreed.

**Comment by bcube2** [comment]
Alright, thank you for your explanation.

Here are my preferences: 6x6x6 regular (i.e. not modified one), 7x7x7 (modified).

If anyone disagree, I am willing to reconsider it :-)

**Comment by mfeather1** [comment]
Fine with me.

**Comment by mfo13** [comment]
OK. I think the desision is yours since you are the developers. I think (just guessing here) that this issue is someway related to the calculation of normals, I'll try to figure out later. By the way I've found another similar issue (overlapping of hidden picutures) also for all the cubes. But since it diverges from the central point here I'll open a new issue when this one is closed.

**Comment by mfo13** [comment]
Well, I think I've found the oringin of the issue. It is not the calculation of normals nor the perspective correction. It is the drawing order. If you change the order numbers in the last row of the drawOrder matrix you'll notice that the issue changes place and even worst scenarios appear. This means that the decisions about the drawing order are wrong in some frontier situations, i.e. shallow observation angles, and probably because of the perspective. It is quite clear in the example bellow. Note that the L layer, in this case, should be drawn at first, however it's been drawn at last, or at least, after the twisting layer.

![227403760-214f41d2-c1fc-4586-838a-bf818fc51738](https://user-images.githubusercontent.com/128325284/227642871-1240db14-42d5-4d01-a387-5133df166a95.jpg)

**Comment by mfeather1** [comment]
Here again it was unclear how to transition from 3x3 to larger cubes and of course my first guess was 0, N, N-1, N-2, ... but as you have seen it does not work properly either, some other setting(s) also need changed apparently (as you said) but unfortunately I have not been able to find the magic combination.  I also do not rule out the possibility that there is something fundamentally wrong with the design because Josef's program was only for 3x3 and transitioning it to larger cubes may require some design changes that I'm not aware of, 3D graphics is not my area of expertise (I'm learning as I go along...)  :)

**Comment by mfo13** [comment]
OK. So I know what is going on; it is the drawing order that doesn't work for all point of views because of the perspective. For example, if you take the perspective out of the game, by setting perspective=50, you'll note that all theses issues disappear, including the another one I said above but didn't show. The same is valid if you set a "divergent" perspective, i.e. perspective>50. Everthing works fine. Because of the "convergent" perspective you need a drawing order for each layer that is facing the observer. So, for the 3x3x3 you need only 3 drawing orders and thus the drawOrder matrix has 3 rows. The 7x7x7 needs 7 drawing orders that must be properly chosen and the same applies for the other cubes. I'll try to fix the code, if it works I'll send you the code and explain in details. If I'm not able to fix I'll explain in details the geometric problem and perhaps you can find an easy way of fixing the code.

**Comment by mfeather1** [comment]
I had received these two links a while ago (indirectly from Josef via Tadeáš ), unfortunately the first link no longer works but it was about what I've included in the third and fourth links.
https://www.coursehero.com/file/8160749/Class7/
https://upload.wikimedia.org/wikipedia/commons/9/93/Comparison_of_graphical_projection

substitutes for broken link:
https://www.cs.ucdavis.edu/~amenta/s12/perspectiveCorrect.pdf
https://www.scratchapixel.com/lessons/3d-basic-rendering/rasterization-practical-implementation/perspective-correct-interpolation-vertex-attributes.html

In the early days of this AnimCubeJS project I was not in a position to be able to implement perspective correct interpolation (as opposed to linear interpolation which is the way it works now) but this is perhaps relevant to the issue at hand.

**Comment by mfeather1** [comment]
I made "modifed 3" without any of the workarounds (black inner faces work just like the original 3x3 program) so the full extent of the problem can be seen.  Setting perspective=50 does indeed fix it as you said.  I have two questions:

1. Should the perspective correction in the paint function (as shown in earlier post) be set to 1.0 /N where N  = cube dimension (1.0 / 7.0 for 7x7 cube) ?

2.  Will using correct perspective interpolation (in previous post) eliminate the need for setting N draworders?

**Comment by mfeather1** [comment]
Added "modified 4" as a possibility, it's not perfect but I don't think perfection is going to be one of our choices.  (no need for pics of the slight gaps along the edges of the inner black faces when turned at certain angles)

**Comment by mfo13** [comment]
Problem solved! I'll send you the code. Even if you set borderwidth=0 it works perfectly without any overlappings of the inner layers. I think you could implement that in the 4, 5 and 6 cubes also. Perhaps there is a better way of doing it, and you probalby can find a more short and efficient code, but the procedure is there. If you don't get the meaning of the comments, just let me know and I'll prepare an explanatory drawing, it is hard to put the idea just in comments.

**Comment by mfeather1** [comment]
Looks Good!  I added it as "modified 5".  I'll look at the code in more detail tomorrow.

**Comment by mfeather1** [comment]
I removed my workarounds from section "find and draw...", if everyone is ok with latest version "modified 6" then I will put back in the other mods mentioned earlier (supertwist & randcube) and make it final.

**Comment by bcube2** [comment]
I think someone of you programmers should set the goal here. Because if the goal is to break the simulator, this will do it: borderwidth=6&scale=10. It is even not a stupidly dumb setting in my opinion because the simulator creator could use it in something like borderwidth=6&scale=10&hint=11&hintborder=1&position=lluuu for example.

**Comment by mfo13** [comment]
I agree with you both. I thin we've already reached a good 7x7x7 simulator. I'm ok with this final result. It was a nice learning process indeed. Thank you.

**Comment by mfeather1** [comment]
Thanks again for your contribution of the 7x7x7 simulator. :)

**Comment by mfo13** [comment]
Just to let you know. I've added the fixing related to the overlapping of inner faces in the scripts of 4x4x4, 5x5x5 and 6x6x6, just for checking, and it works fine. I think this specifc issue is solved for all the cases.

**Comment by mfeather1** [comment]
Yes, I updated those.  I also fixed the problem with  scale/hint (scale=10&hint=11 for example) by applying the cube scale as shown:
 vCopy(copyvec,faceNormals[twistedLayer]);
 vScale(vCopy(fracvec,copyvec), 2.0 / 6.0);
 vScale(vSub(copyvec,vScale(fracvec,i)), scale);  <-- HERE
 vSub(vScale(vCopy(perspEye, eye), 5.0 + persp), copyvec);
 Prod = vProd(perspEye,faceNormals[twistedLayer]);

Also had to change program so all hint faces are displayed prior to the cube being displayed (to eliminate slices of hint faces overlaying cube display).

In the modified versions linked at https://mfeather1.github.io/test/hint/create.html I used a pre-computed table of values (sliceNormals) so it looks like this (for 6x6):

      var orderMode, Prod, memProd, copyvec = [];
      vScale(vCopy(copyvec, eye), 5.0 + persp);
      for (var i = 0; i < 6; i++) {
        vSub(vCopy(perspEye, copyvec), sliceNormals[twistedLayer][i]);
        Prod = vProd(perspEye, faceNormals[twistedLayer]);
        if (i == 0)
          orderMode = (Prod < 0) ? 0 : 5;
        else {
          if ((Prod > 0 && memProd < 0) || (Prod < 0 && memProd > 0)) {
            orderMode = 6 - i;
            break;
          }
        }
        memProd = Prod;
      }

The modified versions also differ slightly in regard to black faces, in the normal versions the black face can be seen briefly after the hint face pops off, in the modified versions no black face can be seen.  Here  is the minor mod of two lines of code for that:

before:
if (vProd(perspEye, faceNormals[i]) < 0) { // draw only hidden faces
if (vProd(perspEye, faceNormals[i]) > 0) { // draw only faces towards us

after:
if (vProd(perspEye, faceNormals[i]) < -(1-scale)) { // draw only hidden faces
if (vProd(perspEye, faceNormals[i]) > -(1-scale)) { // draw only faces towards us

**Comment by mfo13** [comment]
Very nice improvements! I was trying to figure out the issue with the hint facelets but you completely solved it! It looks perfect! I think bcube2 could try to break the simulator by now. ;))

**Comment by mfeather1** [comment]
Your solution to fixing the draw order was exactly what AnimCubeJS needed, no more workarounds!  Looks perfect to me also, but I'll have to wait to see what bcube2 finds, he's got advanced skills when it comes to finding bugs... :)

**Comment by bcube2** [comment]
It´s great to see the progress guys, thank you for your work.

I am super busy with life at the moment, however, I do plan to check out the improvements some day.

**Comment by mfeather1** [comment]
Just as well that you hadn't looked at it yet because I just found that the fix to draw order allows the innerFacePosition function to be eliminated which makes things much simpler, the code for that is now reduced to just the following five lines which are in the section "find and draw..." instead of the function call:
        var v = 0;
        if (i == twistedLayer)
          v = drawLayer / cubeDim;
        else if (i == twistedLayer ^ 1)
          v = (cubeDim - 1 - drawLayer) / cubeDim;

I only updated the modified versions which are at https://mfeather1.github.io/test/hint/create.html (the ones that do not show black faces when the hint faces pop off while rotating the cube), those are intended to be the final versions (when all testing & improving is done).

**Comment by mfo13** [comment]
😯 very nice finding! The code got even more simple! 👏

**Comment by mfeather1** [comment]
I made an updated version of the ACJS Doc which is here:
https://mfeather1.github.io/test/AnimCubeJS-gh-pages/animcubejs.html

In the Intro, I credited you with:
"The 7x7x7 cube was contributed by Marcelo Falcão de Oliveira."

If you would like your name to be a link to your web-site then let me know which url to use.

**Comment by mfo13** [comment]
Thank you very much for the credits! The link is not necessary. :)

**Comment by mfeather1** [comment]
Thank you for the nice new config tool!  :)

**Comment by mfo13** [comment]
You are welcome! I'm thinking about improving the config tool later, regarding facelets and superfacelets, to save the user of entering those long lines of numbers and letters. In the 7x7x7, for example, it must be 294 characters!

**Comment by mfeather1** [comment]
I took the facelet editor from my solver and expanded it to 4x4 to see how it would go, it's on the menu at https://mfeather1.github.io/test/.

**Comment by mfo13** [comment]
Cool!! Good starting basis! Now we need to make it scalable, for any cube, include the whole AnimCube pallet and finally integrate into de config tool... After that doing the same for superfacelets... a long way to go yet. ;)
