### ISSUE TITLE
other cubes possible?

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#3]
This is not really an issue, rather question: in case Michiel will decide not to implement it and Werner will not find the time to work on his simulator, would it be possible to add also 2x2, 4x4 and 5x5 cubes to the Michael´s simulator (as it can already be seen on a simulator by Lucas)?

Several years back, when I talked about it with Josef, he said it is not easily possible in java (and I have no idea how hard it is in JS)...

**Comment by molarmanful** [comment]
I can't do it, at least not by modifying the code from this port; however, I'm looking into it.

**Comment by bcube2** [comment]
It seems Michael is currently working on his webpages, because http://www.irbsystems.com/test2/rc/animcube_customization.html is slightly different than the last time I checked. Therefore I will try to ask Michael about it.

**Comment by bcube2** [comment]
A little report from Michael: he said " ... I'm not familiar enough with Jelinek's code to make a change like that..."

It is bad news considering Josef is busy and probably won't make his java code more suitable for this purpose. But hey, the last thing I can do is to complain, isn't it? Michael's JS simulator is still the best choice for me at the moment, no matter if 2x2x2 - 5x5x5 is possible or not.

Thank you Michael for your reply and your cube simulator.

**Comment by bcube2** [comment]
Good news, everyone. Michael's " ... I'm not familiar enough with Jelinek's code to make a change like that..." is apparently not true anymore (http://irbsystems.com/test2/animcube4/test.html). Does that mean 2x2x2 and 5x5x5 are also possible? 

And what about 4x4x4 Supercube (preferably Gabbasoft style, but of course I will take another style - for example Pochmann - as well)?

**Comment by mfeather1** [comment]
It's not quite ready for prime-time, still working on some issues.  It's not an adjustable size model, just 4x4 for now.

**Comment by mfeather1** [comment]
Ok, now it's ready, try to break it.

**Comment by molarmanful** [comment]
It's amazing as of now. I'll conduct some more tests when I have time, but it's great so far. Nice work!

**Comment by bcube2** [comment]
"Ok, now it's ready, try to break it."

I would if I could, but I can't because you made it unbreakable :-). 

I didn't test all the possible parameters, just the ones I use. No bug found. Easy transformation from Werner's 4x4x4 java applet is a plus. Thank you for layout, very helpful material.

Can I/we use it on the  non-commercial websites?

**Comment by mfeather1** [comment]
Thanks, Benjamin!

**Comment by mfeather1** [comment]
Tadeas,
Glad to hear it!  
Regarding use on non-commercial web-sites, you can use it however you want.

**Comment by mfeather1** [comment]
I added Supercube
http://irbsystems.com/test2/animcube4/test.html

**Comment by bcube2** [comment]
Awesome. Awesome to the max. Happiest day of my life ;-)

First question which comes to my mind: can the triangles be replaced by other objects ("real arrows" for example)? I will play with new parameters and see what tringles can be made..

Thank you, Michael, very much.

**Comment by mfeather1** [comment]
I made arrows like Gabbasoft.

**Comment by bcube2** [comment]
Whoa. Speechless. Gorgeous.

I will test it during the weekend but I don't expect any bug :-)

Edit: I couldn't resist so I had to test it today. As Benjamin was saying, flawless (no bug found). I very much like the darker stickers (adjusted via colorscheme and colors parameters, but I couldn't find an easy way to implement them together with facelets parameter on a scrambled cube. It is not a bug however, it is a feature you/Josef made). Maybe later if I am not too lazy, I will fiddle with it so that i could display those darker stickers...

Other than that, pure beauty.

**Comment by molarmanful** [comment]
Wow, I'm blown away. I'm testing it, but it's flawless as of now.

**Comment by mfeather1** [comment]
Thanks guys. :)  
Tadeas, I added parameter "gabbacolors" which should make it easier to do what you want.  That eliminates the need to use custom colors, it just replaces the normal colors with the gabba colors.
http://irbsystems.com/test2/rc/animcube_customization2.html

**Comment by bcube2** [comment]
Why this "issue" was closed? In the first post it is written: "would it be possible to add also 2x2, 4x4 and 5x5 cubes to the Michael´s simulator (as it can already be seen on a simulator by Lucas)?" 
Some volunteer could likely help with 2x2x2 and 5x5x5 if the isuue/plea is open rather than closed in my opinion...

**Comment by blonkm** [comment]
I have to agree that in open source projects there is a difference between "I can't do it" and "We shouldn't do this". If you feel it's an option to have in the future I think you should leave it open. Check in my rubiks-cube project where I have milestones. https://github.com/blonkm/rubiks-cube/milestones

I even set a version 999 to add joke features, but it's no problem setting targets in the far future. Anyway, whatever you choose, good luck.

**Comment by mfeather1** [comment]
"Why this "issue" was closed?"
To see if anyone still cared. :)
Issue Reopened

**Comment by mfeather1** [comment]
If you're willing to forego the inner black faces, here's a 5x5 cube:
http://irbsystems.com/test2/animcube5/test.html
I'll continue working on the inner black faces but in the meantime this version seems to be quite usable.

**Comment by bcube2** [comment]
Just saw it on your website. Holy moly that looks awesome. Just when Michael Casebolt (mikebolt on github) made his ThreeTwist look awesome on Chrome.

Oh well, sleepless nights (out of excitement) it is, not to mention Benjamin (molarmanful) just made his gCube look awesome on Chrome.

**Comment by mfeather1** [comment]
Updated with inner black faces.

**Comment by bcube2** [comment]
You won't stop amazing us, will you? I will be testing it through the weekend - if I encounter any bug, I will report it here.

Thank you very much for the 5x5 AnimCubeJS, Michael.

**Comment by mfeather1** [comment]
You're welcome!  By the way, I just put in another minor update.

**Comment by bcube2** [comment]
Thank you for letting us know.

Also, thank you very much for a 2x2x2. I am going to test it through the weekend. 

I am going to tell the (speed)cubing world about this project. Let they like it as much as I do.

New era of simulating a Rubik's cube on the web has begun.

P.S. is there anything I can do in return? I would like to appreciate your hard and excellent work somehow. Name it, both material or natural "reward" is fine. That's the smallest thing I can do and you deserve it no doubt.

**Comment by mfeather1** [comment]
I updated all of them, fixed the superfacelets parameter in 3x3, updated 4x4 with the version that was in development (advanced modes) and a minor update to 5x5 so it wasn't trying to access the clean.css file (just the animcube5.nocache.js was updated).  As for reward, sustenance of my overly-inflated ego is reward enough. :)  When your work as the project publicist makes us both household names with regard to cubing then we will be in the limelight (or maybe you already are?).

**Comment by bcube2** [comment]
"my overly-inflated ego"

Two possible explanations. Either I don't know you well or you are not telling the true in this case :-P.

"maybe you already are in the limelight with regard to cubing"

Hehe, no.

Seems to me this issue/question/request can be closed now, I didn't see any error on a regular 2x2x2 - 5x5x5 cubes and I didn't see any error on a 4x4x4 Supercube either (I have been testing 2x2x2, 3x3x3 and 5x5x5 Supercubes only on Micheal's website, however, I didn't find any bug either).

**Comment by mfeather1** [comment]
Ok, great!  I'll leave this open a little while longer in case anything comes up.
