### ISSUE TITLE
Customised sticker roundness

### ISSUE THREAD

**Issue by tarasovladislav** [cubing/AnimCubeJS#34]
Hi

Did anyone work on customised sticker roundness? Would be great since for now with square stickers it looks kinda old :D

**Comment by bcube2** [comment]
Hi tarasovladislav,

[Florian mod](https://animcubejs.cubing.net/sources/codes/enhancement/florian.html) has been added to the [Enhancement](https://animcubejs.cubing.net/animcubejs.html#enhancement) section, see if you like it better.

**Comment by tarasovladislav** [comment]
Hi, it looks good, thanks!

**Comment by tarasovladislav** [comment]
@bcube2 

Hi, can this florian mode be used also for other cube sizes? 2-7?

**Comment by bcube2** [comment]
Yeah, the Florian mod can actually be fully customized for each cube size by programmers/developers - you can round whichever inner corners however you like it.

For instance, you can create/emulate the following configuration. Notice how there are 3 different hole sizes on the picture.

![jj](https://github.com/user-attachments/assets/ab6d07b0-652d-436a-8693-6ce63e8d36ed)
