### ISSUE TITLE
Pause between moves in Play mode? 

### ISSUE THREAD

**Issue by tarasovladislav** [cubing/AnimCubeJS#35]
HI

Is it possible to add pause between moves during playing?  Lets say I want it playing but i want 500ms small pause between moves so there is little time for user to think what to rotate

**Comment by bcube2** [comment]
Hi,

in the [move](https://animcubejs.cubing.net/animcubejs.html#move) parameter section, look up the dot character.

[Demo](https://animcubejs.cubing.net/sources/codes/enhancement/parameters/cube3.html?move=R.R..R...R....U&movetext=1&buttonheight=20&textsize=14)

**Comment by tarasovladislav** [comment]
@bcube2 Thanks, it works, will take a look into source as well to modify how long the pause is, maybe users would want to make it lower than half of the rotation time.
