### ISSUE TITLE
Another way of showing hidden faces (backView = "side-by-side")

### ISSUE THREAD

**Issue by tarasovladislav** [cubing/AnimCubeJS#39]
Hi

How do you think, would it be possible to make something similar what cubingjs has (backView = "side-by-side"). 
So you have 2nd cube which actually is same cube but from other angle and still can rotate the cube

![image](https://github.com/cubing/AnimCubeJS/assets/141230039/34d66a51-a755-49f5-ad0e-34e64d88c3d7)

https://codepen.io/cubing/pen/vYyKBMd

**Comment by mfeather1** [comment]
try this
[backview.zip](https://github.com/user-attachments/files/15944921/backview.zip)

**Comment by mfeather1** [comment]
[backview.zip](https://github.com/user-attachments/files/15961026/backview.zip)
Updated so Y movements done to the second cube work as expected (as opposed to rotating in opposite direction).  Also reduced the space between  the cubes which minimizes the possibility of rotation not working properly (both cubes rotate opposite of Y movement if drag starts from the gap).

**Comment by mfeather1** [comment]
This seems to have eliminated the gap problem altogether (add the if statement in mousedown).
```
mousedownId = e.target.parentNode.id;
if (mousedownId != 'c1' && mousedownId != 'c2')
  mousedownId = 'c1';
```

**Comment by bcube2** [comment]
Works for me. Closing.
