### ISSUE TITLE
clickable time-line possible?

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#4]
Another rather unimportant question (which doesn´t really bother me but I can imagine it could be helpful in some cases – if the algorithm is 180 moves long, for example): would it be possible to add clickable time-line?

By that I mean the blue parts which got visible after each move (on index.html by molarmanful). If the end user wants to jump at move no. 100 for example, he has to wait some time (99 moves to be specific) instead of jumping there directly...

Java applets offered such function (just sayin´).

**Comment by molarmanful** [comment]
Oh, sort of like alg.cubing.net...
I'm looking into it. It'll have to be external (basically not in the applet itself), but controlled by some slider outside of the applet. I'll have a demo ready to explain better.

**Comment by bcube2** [comment]
Oh, it seems I bothered you for nothing, because right now I noticed clickable time-line works in case of myself defined simulators (offline version). I use the parameters which can be found here: hlavolam.maweb.eu/rubikova-kostka-3x3x3 (see the source code). Online version will be available on 22.7. (as I said elsewhere on this github).

Hmm, it seems to be related to offline/online version. In your index.html, clickable time line doesn´t work online, however, it works offline...

**Comment by bcube2** [comment]
I hope Michael will not be offended if I re-send his reaction which was sent to me via e-mail:

"... That's the clickprogress option that I added, I have it set to 0 for my web-site but the default is to work the same way as the original applet, so either leave it out of the config file or set it to:
clickprogress=1

That is documented here:
http://irbsystems.com/test2/rc/animcube_customization2.html"

Thank you Michael for a solution. Thank you molarmanful for trying to solve this "issue".

P.S. I didn´t use config file but I guess I will. Or I will just add the parameter by hand one time - I can imagine it can be added to the rest of the simulators automatically easily :-) 

P.S.2. actually, from what Michael said I think I can not change clickprogress at all... I will try and see when my website is online...
