### ISSUE TITLE
Special buttons to trigger the cube's movements

### ISSUE THREAD

**Issue by BakiTANRISEVEN** [cubing/AnimCubeJS#41]
<!doctype html>
<html>
<head>
 <meta name=viewport content="width=device-width, initial-scale=1">
 <script src=AnimCube3.js></script>
 <style> 
  body {margin-left: 10%; margin-right: 10%;}
  p {margin:0; text-align: justify;}
 </style>
</head>
<body>
<center>
<font size=+2>AnimCubeJS Move Buttons</font>
<br><br>
<table>
 <tr>
  <td style=text-align:center>Cube 1</td>
  <td width=50>
  <td style=text-align:center>Cube 2</td>
 </tr>
 <tr>
  <td><div id=c1 style="width:180px; height:180px"></div></td>
  <td>
  <td><div id=c2 style="width:180px; height:180px"></div></td>
 </tr>
</table>
<br>
Cube 1:&nbsp;
<button onclick="cubeMove('c1','R')">R</button>
<button onclick="cubeMove('c1','L')">L</button>
<button onclick="cubeMove('c1','U')">U</button>
<button onclick="cubeMove('c1','D')">D</button>
<button onclick="cubeMove('c1','F')">F</button>
<button onclick="cubeMove('c1','B')">B</button>
<button onclick="newPos('c1')">Snap</button>
<button onclick="cubeReset('c1')">Reset</button>
<br><br>
Cube 2:&nbsp;
<button onclick="cubeMove('c2','R')">R</button>
<button onclick="cubeMove('c2','L')">L</button>
<button onclick="cubeMove('c2','U')">U</button>
<button onclick="cubeMove('c2','D')">D</button>
<button onclick="cubeMove('c2','F')">F</button>
<button onclick="cubeMove('c2','B')">B</button>
<button onclick="newPos('c2')">Snap</button>
<button onclick="cubeReset('c2')">Reset</button>
<br><br>
<p>Note:<br>
If the cube has been rotated (via mouse or touch) prior to pressing a move
button then the cube will "snap" into position when the move is applied.
To ensure the correct snap position, rotate so the front face is largest.
To snap prior to doing a move, use the Snap button.</p>
<br>
<script>
var acjs_cube = [];
var acjs_startAnimation = [];
var acjs_stopAnimation = [];
var acjs_move = [];
var acjs_getMove = [];
var acjs_doMove = [];
var acjs_eye = [];
var acjs_eyeX = [];
var acjs_eyeY = [];
var acjs_initialEye = [];
var acjs_initialEyeX = [];
var acjs_initialEyeY = [];
var acjs_paint = [];
var acjs_vCopy = [];
var acjs_vNorm = [];
var acjs_vMul = [];
var acjs_clear = [];
var acjs_get_var = [];
var tmp_pos = {eye:[], eyeX:[], eyeY:[]};
var params = '&buttonbar=0&counter=0&bgcolor=ffffff&snap=1';
var cubePosArr = [
  // the 24 cube positions for detecting which position the cube is in
  //   eyeX          eyeY 
  [[ 1,  0,  0], [ 0, -1,  0]], // F
  [[ 0, -1,  0], [-1,  0,  0]], 
  [[-1,  0,  0], [ 0,  1,  0]], 
  [[ 0,  1,  0], [ 1,  0,  0]], 
  [[-1,  0,  0], [ 0, -1,  0]], // B
  [[ 0, -1,  0], [ 1,  0,  0]],
  [[ 1,  0,  0], [ 0,  1,  0]],
  [[ 0,  1,  0], [-1,  0,  0]],
  [[ 1,  0,  0], [ 0,  0,  1]], // U
  [[ 0,  0,  1], [-1,  0,  0]],
  [[-1,  0,  0], [ 0,  0, -1]],
  [[ 0,  0, -1], [ 1,  0,  0]],
  [[ 1,  0,  0], [ 0,  0, -1]], // D 
  [[ 0,  0, -1], [-1,  0,  0]],
  [[-1,  0,  0], [ 0,  0,  1]],
  [[ 0,  0,  1], [ 1,  0,  0]],
  [[ 0,  0, -1], [ 0, -1,  0]], // L
  [[ 0, -1,  0], [ 0,  0,  1]],
  [[ 0,  0,  1], [ 0,  1,  0]],
  [[ 0,  1,  0], [ 0,  0, -1]],
  [[ 0,  0,  1], [ 0, -1,  0]], // R
  [[ 0, -1,  0], [ 0,  0, -1]],
  [[ 0,  0, -1], [ 0,  1,  0]],
  [[ 0,  1,  0], [ 0,  0,  1]]
];
var reposMove = [
  // move sequences to reposition the cube corresponding to above array
  "", "Y", "Y2", "Y'", "Z2", "Z2Y", "Z2Y2", "Z2Y'", 
  "X'", "X'Y", "X'Y2", "X'Y'", "X", "XY", "XY2", "XY'",
  "Z'", "Z'Y", "Z'Y2", "Z'Y'", "Z", "ZY", "ZY2", "ZY'"
];
AnimCube3('id=c1' + params);
AnimCube3('id=c2' + params);
function cubeMove(id, mv) {
  if (getPos(id) != 0)
    newPos(id);
  acjs_move[id][0] = acjs_getMove[id](mv, 0)[0]; 
  acjs_startAnimation[id](0);
}
function newPos(id) {
  var pos = getPos(id);
  cubeRepos(id);
  var move = acjs_move[id];
  move = acjs_getMove[id](reposMove[pos], 0);
  acjs_doMove[id](acjs_cube[id], move[0], 0, move[0].length, false);
  acjs_paint[id]();
}
function cubeRepos(id) {
  var vCopy = acjs_vCopy[id];
  vCopy(acjs_eye[id], acjs_initialEye[id]);
  vCopy(acjs_eyeX[id], acjs_initialEyeX[id]);
  vCopy(acjs_eyeY[id], acjs_initialEyeY[id]);
  acjs_paint[id]();
}
function cubeReset(id) {
  if (acjs_get_var[id]('animating')) {
    acjs_stopAnimation[id]();
    setTimeout(cubeReset, 10, id);
  }
  else
    acjs_clear[id]();
}
function getPos(id) {
  var vCopy = acjs_vCopy[id];
  var vNorm = acjs_vNorm[id];
  var vMul = acjs_vMul[id];
  var e=[], eX=[], eY=[];
  vCopy(e, acjs_eye[id]);
  vCopy(eX, acjs_eyeX[id]);
  vCopy(eY, acjs_eyeY[id]);
  if (centerEye(e) != centerEye(eX))
    vNorm(vMul(eY, e, eX));
  else {
    centerEye(eY);
    vNorm(vMul(eX, eY, e));
  }
  for (var i=0; i < cubePosArr.length; i++) {
    var bX = cubePosArr[i][0];
    var bY = cubePosArr[i][1]
    if (eX[0] == bX[0] && eX[1] == bX[1] && eX[2] == bX[2] &&
        eY[0] == bY[0] && eY[1] == bY[1] && eY[2] == bY[2])
    break;
  }
  return i;
}
function centerEye(arr){
  let abs_arr = arr.map((el)=>Math.abs(el));
  let index = abs_arr.indexOf(Math.max(...abs_arr));
  let sign = arr[index] > 0 ? 1 : -1;
  arr.forEach((el, i)=>{
    arr[i] = i == index ? sign : 0;
  });
  return index;
}
</script>
</center>
</body>
</html>

Hello; what should be the codes for the L' R' F' B' U' D' and L2 R2 F2 B2 U2 D2 rotations of the cube?

**Comment by mfeather1** [comment]
For buttons :
```
<button onclick="cubeMove('c1','R\'')">R'</button>&nbsp;
<button onclick="cubeMove('c1','L\'')">L'</button>&nbsp;
<button onclick="cubeMove('c1','U\'')">U'</button>&nbsp;
<button onclick="cubeMove('c1','D\'')">D'</button>&nbsp;
<button onclick="cubeMove('c1','F\'')">F'</button>&nbsp;
<button onclick="cubeMove('c1','B\'')">B'</button>&nbsp;
<br>
<button onclick="cubeMove('c1','R2')">R2</button>&nbsp;
<button onclick="cubeMove('c1','L2')">L2</button>&nbsp;
<button onclick="cubeMove('c1','U2')">U2</button>&nbsp;
<button onclick="cubeMove('c1','D2')">D2</button>&nbsp;
<button onclick="cubeMove('c1','F2')">F2</button>&nbsp;
<button onclick="cubeMove('c1','B2')">B2</button>&nbsp;
```
For keyboard input, just hit the letter twice for half-twist or three times for counter-clockwise.  

Another way is to make the shift key do counter-clockwise moves:
```
function keydown(e) {
  if (gid == '')
    return;
  var mlist = ['x','y','z','r','l','u','d','f','b'];
  if (mlist.includes(e.key.toLowerCase())) {
    var mv = e.key;
    if (['r','l','u','d','f','b'].includes(mv))
      mv = mv.toUpperCase();
    else if (['R','L','U','D','F','B'].includes(mv))
      mv += "'";
    cubeMove(gid, mv);
  }
}
```
That still requires hitting key twice for half-twists.

While it would be nice to use the Ctrl and Alt keys as modifiers that does not work too well because the browser and window manager overrides several of them for various things.

If you can think of another way to do it, it can likely be programmed but that's all I can think of at the moment.

**Comment by BakiTANRISEVEN** [comment]
> For buttons :
> 
> ```
> <button onclick="cubeMove('c1','R\'')">R'</button>&nbsp;
> <button onclick="cubeMove('c1','L\'')">L'</button>&nbsp;
> <button onclick="cubeMove('c1','U\'')">U'</button>&nbsp;
> <button onclick="cubeMove('c1','D\'')">D'</button>&nbsp;
> <button onclick="cubeMove('c1','F\'')">F'</button>&nbsp;
> <button onclick="cubeMove('c1','B\'')">B'</button>&nbsp;
> <br>
> <button onclick="cubeMove('c1','R2')">R2</button>&nbsp;
> <button onclick="cubeMove('c1','L2')">L2</button>&nbsp;
> <button onclick="cubeMove('c1','U2')">U2</button>&nbsp;
> <button onclick="cubeMove('c1','D2')">D2</button>&nbsp;
> <button onclick="cubeMove('c1','F2')">F2</button>&nbsp;
> <button onclick="cubeMove('c1','B2')">B2</button>&nbsp;
> ```
> 
> For keyboard input, just hit the letter twice for half-twist or three times for counter-clockwise.
> 
> Another way is to make the shift key do counter-clockwise moves:
> 
> ```
> function keydown(e) {
>   if (gid == '')
>     return;
>   var mlist = ['x','y','z','r','l','u','d','f','b'];
>   if (mlist.includes(e.key.toLowerCase())) {
>     var mv = e.key;
>     if (['r','l','u','d','f','b'].includes(mv))
>       mv = mv.toUpperCase();
>     else if (['R','L','U','D','F','B'].includes(mv))
>       mv += "'";
>     cubeMove(gid, mv);
>   }
> }
> ```
> 
> That still requires hitting key twice for half-twists.
> 
> While it would be nice to use the Ctrl and Alt keys as modifiers that does not work too well because the browser and window manager overrides several of them for various things.
> 
> If you can think of another way to do it, it can likely be programmed but that's all I can think of at the moment.

Thank you very much.

**Comment by mfeather1** [comment]
I spoke to soon, ctrl & alt can be used by using e.preventDefault() in keydown function to override browser shortcuts.  If you are only using buttons then you don't need this but I'm adding this for future reference.  :)

For this, there is also a minor mod to the mousedown function (added gid = '';).
```
function mousedown(e) {
  gid = '';
  if (typeof e.target.parentNode.id != 'undefined') {
    var s = e.target.parentNode.id;
    if (typeof acjs_parNode[s] != 'undefined')
      gid = s; 
  }
}
```
In keydown function, ctrl key is added for half-turns, alt can be used the same way (just change e.ctrlKey to e.altKey).
```
function keydown(e) {
  if (gid == '')
    return;
  var mlist = ['x','y','z','r','l','u','d','f','b'];
  if (mlist.includes(e.key.toLowerCase())) {
    e.preventDefault();
    var mv = e.key.toUpperCase();
    if (e.ctrlKey)
      mv += "2";
    else if (!mlist.includes(e.key))
      mv += "'"; 
    cubeMove(gid, mv);
  }
}
```

**Comment by BakiTANRISEVEN** [comment]
> Yakında konuştum, ctrl ve alt, tarayıcı kısayollarını geçersiz kılmak için keydown fonksiyonunda e.preventDefault() kullanılarak kullanılabilir. Sadece düğmeleri kullanıyorsanız buna ihtiyacınız yok ama gelecekte referans olması için bunu ekliyorum. :)
> 
> Bunun için mousedown fonksiyonuna küçük bir mod daha eklendi (gid = '';).
> 
> ```
> function mousedown(e) {
>   gid = '';
>   if (typeof e.target.parentNode.id != 'undefined') {
>     var s = e.target.parentNode.id;
>     if (typeof acjs_parNode[s] != 'undefined')
>       gid = s; 
>   }
> }
> ```
> 
> Keydown fonksiyonunda yarım dönüşler için ctrl tuşu eklenmiştir, alt tuşu da aynı şekilde kullanılabilir (e.ctrlKey'i e.altKey olarak değiştirmeniz yeterlidir).
> 
> ```
> function keydown(e) {
>   if (gid == '')
>     return;
>   var mlist = ['x','y','z','r','l','u','d','f','b'];
>   if (mlist.includes(e.key.toLowerCase())) {
>     e.preventDefault();
>     var mv = e.key.toUpperCase();
>     if (e.ctrlKey)
>       mv += "2";
>     else if (!mlist.includes(e.key))
>       mv += "'"; 
>     cubeMove(gid, mv);
>   }
> }
> ```

This information was helpful. Thank you for your work and efforts.
