### ISSUE TITLE
Tracking clicks

### ISSUE THREAD

**Issue by tarasovladislav** [cubing/AnimCubeJS#42]
Hei! 

Is there option to understand on which facelet user clicks, so I can let's say recolor it.

For recoloring I use this. 
function update_facelet(side, square, color) {
        acjs_cube[""][side][square] = color;
        acjs_paint[""]();
      }

**Comment by bcube2** [comment]
Hi,

in the [Enhancement section](https://animcubejs.cubing.net/animcubejs.html#enhancement) of the documentation there is a link to this [Facelet Editor](https://animcubejs.cubing.net/sources/codes/enhancement/facelet_editor.html?pallet=roywgbld).

**Comment by tarasovladislav** [comment]
Yes, I saw that, working with it at the moment, but what i mean, is when actually clicking on the actual cube (Canvas itself)

**Comment by mfeather1** [comment]
Here is an example of how to do it with a modified version of AnimCube3.js.
[facelet_editor2.zip](https://github.com/user-attachments/files/16715743/facelet_editor2.zip)

**Comment by tarasovladislav** [comment]
@mfeather1 This is amazing! Thank you so much! 
If not hard, can you, please, mention what changes you made? In case I would like to add this to other cube sizes, if no,  its fine, I will take my time and find out!

**Comment by mfeather1** [comment]
It works similar to dragAreas.  In function fixBlock, the coordinates for the four corners of each facelet are stored in new array faceletAreas.  In function mousedown, the list of areas are scanned to see if the pointer position is within one of them and if so it sets the color for that facelet.  The "point in polygon" function was borrowed from: https://wrfranklin.org/Research/Short_Notes/pnpoly.html (as indicated in A3mod.js).

**Comment by mfeather1** [comment]
This example has both 3x3 & 4x4 cubes. I made some minor mods so that the code is the same for any size cube except for where it references objects on the web page (which differ in this example due to having two cubes with separate color selection dropdowns & facelet display fields).
[facelet_editor2.zip](https://github.com/user-attachments/files/16738806/facelet_editor2.zip)

**Comment by mfeather1** [comment]
This version supports all cube sizes (2x2-7x7) using only one cube with a dropdown list to change the size, also added supercube.  The code mod is exactly the same in all six programs (A[2-7]mod.js).
[facelet_editor2.zip](https://github.com/user-attachments/files/16799319/facelet_editor2.zip)

**Comment by bcube2** [comment]
Works for me. Closing.
