### ISSUE TITLE
Identifying the correct config parameter path on Docusaurus based site

### ISSUE THREAD

**Issue by mjstraughan** [cubing/AnimCubeJS#44]
There seems to be a small bit of incompatibility between AnimCubeJS and Docusaurus, as seen in a couple of my previous issue submissions.

For this one, I have tried implementing the config parameter into the cubinghistory.com applets. I have created a file named ReconstructionConfig.txt with the various parameters that I want to be the default. I have tried placing the file in the root of my project, in the same folder as the page with the applet, and also in the folder named "static". I have tried various paths with the config parameter and nothing so far gets the parameter to work. Examples below of paths that I have tried after config=:

ReconstructionConfig.txt
/ReconstructionConfig.txt
../ReconstructionConfig.txt
../../ReconstructionConfig.txt
../../../ReconstructionConfig.txt
../../../../ReconstructionConfig.txt
static/ReconstructionConfig.txt
/static/ReconstructionConfig.txt
../../static/ReconstructionConfig.txt

Not sure if this helps, but I have .html files saved and linked on the site. Those have always had to be saved in the "static" folder for them to be used as links on Docusaurus. For example, on one of the method pages I have <a href="/archive/nooks_zz_new.htm">here</a> to link to that .htm file that's saved in the static/archive folders.

**Comment by mfeather1** [comment]
It appears to be working on a local copy of your website where I added config=../../ReconstructionConfig.txt to one of  the pages.  Do you have an example of a page where it does not work as expected?

**Comment by bcube2** [comment]
> It appears to be working on a local copy of your website where I added config=../../ReconstructionConfig.txt to one of the pages.

What page you are referring to, please? Where do you have the configuration file, please? Are you sure that the settings from the configuration file are applied to the simulator? I have a local copy working too, but I wasn´t able to set it all up.

**Comment by mjstraughan** [comment]
It is working now using that setting. Really strange. bcube and I went through it, testing that exact setup. I must have not used the right combination of that path with the file in the correct location. Mysterious.

**Comment by bcube2** [comment]
> What page you are referring to, please? Where do you have the configuration file, please? Are you sure that the settings from the configuration file are applied to the simulator? I have a local copy working too, but I wasn´t able to set it all up.

Oooooh, now I see it. My mistake. I was using the setting bgcolor=ff00ff in my own testing configuration file, only to realize now mjstraughan is using a modified AnimCube3.js file that is using transparent background - so my setting could not be seen when tested (because ironically enough mjstraughan was also using the buttonbar=0 setting in his page).

Anyway, I got it working too using this setup: configuration file placed in the CubingHistory/static directory, and relative path in the *.md file pointing to the CubingHistory directory.

This Docusaurus-based setup is not what I and mjstraughan were aiming for at the beginning.
