### ISSUE TITLE
rotation of the cube for mobile users possible?

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#5]
Not really an issue, rather question. As mentioned in speedsolving.com thread (see first site, 6th post, number 11), I would like to ask if edit parameter is set to zero, would it be possible to rotate the cube by touching it and moving a finger in case of mobile users?

**Comment by mfeather1** [comment]
I have this working on my web-site (with Acer tablet using Chrome/Android), check it out.

**Comment by bcube2** [comment]
It looks amazing. Thank you for doing that. Out of curiosity (can not test it right now) what would happen if edit parameter is set to one on mobile devices (won't be my case probably)?

As usually, updating of JS files is sufficient for getting it on my/other website?

And a little offtopic: as asked before, is clean.css really neccessary in order to show your simulator on my/other website?

**Comment by mfeather1** [comment]
edit=1 (turning of individual faces) works also

yes, updating of JS files should be sufficient for getting it on your/other website

clean.css is something gwt creates and, as was mentioned earlier, it generates an error in the log file if it is not there.  I have not as yet looked into the possibility of eliminating it but will do so now.

**Comment by mfeather1** [comment]
I made an update, if you search the latest animcube.nocache.js on my site, clean.css is no longer in it.  The other JS files were not affected.

**Comment by bcube2** [comment]
Thank you for an explanation and elimination of clean.css.

I was actually asking about the possiblility of rotating the cube if edit=1 on mobile devices but today I can test it on my own...

Benjamin, do you think you could give Michael the "administrator rights" for this github because of frequent updates? Your github homepage for his simulator is constantly outdated :-P On the other hand, the trend of frequent updates might not be continuing because you simply can not update forever  what is perfect now.

**Comment by mfeather1** [comment]
Yes, edit=1 works on mobile devices (on mine anyways).  I think github updates should only be made after changes have been tested and approved (by you since you're the tester :)

**Comment by bcube2** [comment]
"Yes, edit=1 works on mobile devices"

I think I was not clear enough yet. On PC, you can have edit=1 and you're still able to rotate the cube (by right clicking). I guess it is not possible on mobile device since there is only one "action" (tapping) instead of two (left clicking and right clicking) in case of mouse.

So I was asking if you have to choose between either rotating the cube (edit=0) or rotating the layer (edit=1), because on computer you don't have to choose between these two options.

I can imagine it would still be possible as it is in case of PC (i.e. you could still rotate the cube if edit=1 - see Werner's WebGL cube for example), but it is not worth it in my opinion. I think current situation (you have to choose between rotating the cube or layer) is the best for mobile users (in case of a tutorial).

**Comment by mfeather1** [comment]
For me the way it works on PC is, cube rotation by left-clicking starting outside the cube (but inside the window that the cube is in) and dragging (holding down the button) in the desired direction.  A layer is turned by left-clicking starting from a location on the layer (touching the cube) and dragging in desired direction.  Right-clicking is not used at all for cube manipulation, it brings up a Firefox menu that says "View Image", "Save Image As", etc. (although I just noticed that right-clicking on the java version does not bring up the menu and can be used to turn the whole cube (in addition to the aforementioned method)).

Edit: Also, if Edit=0 then the cube can be turned by left-clicking starting anywhere within the cube window

On this Acer tablet I can either turn the cube or a layer by touching and sliding finger across the screen using the above rule (start outside cube to turn cube, start inside cube (touching cube) to turn a layer.

**Comment by mfeather1** [comment]
I moved the JS files on my web-site they are now in:
http://irbsystems.com/test2/rc/AnimCube/
(removed the animcube subdirectory)

**Comment by molarmanful** [comment]
@mfeather1 You have full access to the code, so you can go ahead and edit.

**Comment by bcube2** [comment]
"For me the way it works..."

Yeah, for me it works similarly. For some reason I always used the right mouse button to rotate the cube in java version. It still partially works in JS version too. 

Sorry for a confusion I made - next time I will be more careful when talking about java version and not mentioning it anywhere...

So, if edit=1, your simulator behaves as Werner's one. Personally I find edit=0 better for mobile users (who are searching for a tutorial instead of playable cube), so I will probably stick with that. Maybe I will make a note for users that the cube can be rotated when touched and dragged in the near surrounding, thus edit=1 could be present. 

Anyway, this issue/question is solved :-)

**Comment by mfeather1** [comment]
@molarmanful  Ok, I'll see if I can figure out how to do admin.

**Comment by mfeather1** [comment]
@bcube2 
"Yeah, for me it works similarly. For some reason I always used the right mouse button to rotate the cube in java version. It still partially works in JS version too."

Have you done something to avoid the menu from popping up on right-click?  I just found that it can be disabled by adding: oncontextmenu="return(false);" to the cube.html file.  

I also noticed that It stops working when the cursor leaves the cube window but I found a way to fix that too with an update to the JS files.   Do you want to test that too? If so I would need to move the JS files to my web-site so you can access them (they are only in my local test area right now).

**Comment by mfeather1** [comment]
@molarmanful
I cloned the repository to a local directory, after I copy the updated JS files there I was going to do a "git push".  Is there any reason not to do it that way?

**Comment by molarmanful** [comment]
@mfeather1 Go ahead! I'm fine with it.

**Comment by mfeather1** [comment]
Can't get it to work, just keeps saying "Everything up-to-date".

Went through list of examples here:
https://www.kernel.org/pub/software/scm/git/docs/git-push.html

git push
Everything up-to-date

git push origin
Everything up-to-date

git push origin :
Everything up-to-date

git push origin gh-pages
Everything up-to-date

git push origin HEAD
Everything up-to-date

git push --all origin
Everything up-to-date

**Comment by mfeather1** [comment]
From the diagram, it looks like I need to add & commit before doing push. I'll continue with this tomorrow.

http://stackoverflow.com/questions/2745076/what-are-the-differences-between-git-commit-and-git-push

**Comment by bcube2** [comment]
"Have you done something to avoid the menu from popping up on right-click? "

No, I haven't. 

"I also noticed that It stops working when the cursor leaves the cube window"

That's why I wrote it works partially in JS version too.

"Do you want to test that too? "

Either way is fine :-). I just like right clicking for rotating the cube better - but as I said, its kind of impossible to have it on touch devices too (because there is no second button in comparison with the mouse). Oh, btw I remembered where I got this habit about right clicking to rotate the cube: apparently I play too much. I couldn't find a java simulator (which I actively use) that couldn't support right clicking for rotating the puzzle. It seems to be just a strong habit. 

http://twistypuzzles.com/forum/viewtopic.php?f=8&t=24876. I recommend pCubes but there are lots of beautiful simulators too.

**Comment by mfeather1** [comment]
Ok GitHub is updated.

Then I made another change to fix right-click which can be tested on my web-site.  If that looks ok, then I'll update GitHub again tomorrow.

**Comment by bcube2** [comment]
It looks ok Michael, assuming it is not possible to get rid of that popping-up menu when right button is clicked-down and the mouse cursor is outside the window of a simulator (correct me if I am wrong and it is possible to get rid of that popping-up menu).

One observation though (not a serious bug or anything): when several simulators are on a page - see http://irbsystems.com/test2/rc/edges_6c.html for example, and trying to rotate the cube (in this particular case by either left or right mouse button), the cube does not rotate when entering and being in another simulator window. After leaving another simulator window, the initial cube will rotate as expected.

**Comment by mfeather1** [comment]
To eliminate the pop-up menu on right-click when the cursor is not on a cube window you need to make the body statement in each of your web pages:
&lt;body oncontextmenu="return(false)"&gt;

The issue of the cube not rotating when entering another cube window I have not found a way to fix.  It does work properly on the touch screen though.

**Comment by bcube2** [comment]
"To eliminate the pop-up menu on right-click when the cursor is not on a cube window you need to make the body statement in each of your web pages:
<body oncontextmenu="return(false)">"

Oh, silly me - I somehow forgot you already mentioned this way like 5 posts ago. In your  first post, you suggested putting it inside cube.html instead of each page. For several reasons I find it better (to put it only inside cube.html) so I will try it and see if it is sufficient... Thank you for reminding though.

"The issue of the cube not rotating when entering another cube window I have not found a way to fix."

Doesn't really matter ;-). I still love it :-P

Edit: okay, I can see how oncontextmenu is related to the body of either cube.html or a webpage where the simulator is put. I don't want to constrain the viewer at all. On the other hand, there are several ways how to do the same as right click, even if right click is disabled. So I am in ethical pickle here :-/. A good compromise seems to be using of oncontextmenu in cube.html but not in a website itself.

**Comment by mfeather1** [comment]
I neglected to mention that with the latest update to AnimCube (on my web-site) that it is not necessary to use oncontextmenu in cube.html to avoid the pop-up (within cube window), the change to AnimCube (JS files) should be preventing it. Also, right-click should continue to rotate the cube when you drag the mouse outside the cube window.

For my web-site, I have chosen the same compromise that you spoke of, context menu disabled within cube windows but enabled on the rest of the page (outside of cube windows).

**Comment by bcube2** [comment]
Everything understood. Looking forward to seeing the latest/updated version of JS files here on github.

Also, I can confirm everything behaves as you describe it in case of your website.

**Comment by mfeather1** [comment]
Ok GitHub updated.
