### ISSUE TITLE
control buttons are not working on Android

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#7]
Due to the cancellation of my vacation (grr) I decided to put my website online (see hlavolam.maweb.eu/rubikova-kostka-3x3x3). I am currently using latest JS files (6 of them). I am facing two issues: one is described in issue no. 6 on this github and the second is that the control buttons are not working on Android (didn´t try on another mobile device yet). Control buttons are not working even on Michael´s website for me.

Edit: you can't find new JS files anymore on my site. I temporarily switched to the old ones, because control buttons are working there for Android.

**Comment by bcube2** [comment]
Simultaneously solved with issue no. 6. Benjamin, you might want to update all JS files everywhere on this github.

**Comment by molarmanful** [comment]
Cool, I've finished updating.

**Comment by mfeather1** [comment]
Looks good except cube.html needs the resizeFrame() function
and the onload call for the retina scaling to work.

shown here:
http://www.irbsystems.com/test2/retina/cube.html
(view source)
