### ISSUE TITLE
alignment of a layer after a move

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#9]
People without a real cube, who will use a computer simulator to solve the cube instead, would maybe appreciate if there were some authomatical alignment after moving a layer. Right now they can either perform a move precisely or make another additional move (second part of the move to be specific) becuase the layer is stuck inbetween.

If it is too difficult to make, fotget it. People will be forced to perform a precise move, which is a good habit for a real cube anyway ;-)

**Comment by mfeather1** [comment]
It works the same as the original, doesn't it?  It does auto-align but it has to be pretty close.

**Comment by bcube2** [comment]
"It works the same as the original, doesn't it?"
Yes, it does. In other words potentional end users would maybe appreciate better alignment in case of Java applets too.

 " It does auto-align but it has to be pretty close."
True, thus sometimes it is required to do another part of the intended move. From my experience, these "alignment/partial" moves can be very annoying.

As I was saying, it is not worth it to make better from alignment point of view (see  pCubes for example) if it is too much work.

**Comment by mfeather1** [comment]
Try this:
http://www.irbsystems.com/test2/snap/test.html
I added parameter "snap"

**Comment by bcube2** [comment]
For me as a solver is a usage of snap parameter better, thank you for doing it. The solves are more fluent now, without lock-ups.

If I was a nitpicker, I would say the motion is a little bit fast. Maybe I am just influenced by other simulators I use (Werner's one for instance), so other people would be more suitable to say if it is excellent or "only" good. Maybe everyone's taste is different. Maybe everyone's solving style is different as well (especially true for a real cubes).

Anyhow, don't forget to update your new parameters page ;-)
